image: node:latest

stages:
    - test

test:
    stage: test
    script:
        - "npm install"
        - "npm run lint"
        - "npm run build"
        - "npm run test"
    artifacts:
        paths:
        - dist/
        - dist-esm/
        - dist-umd/
